//////////////////////////////////////////////////
// !!!!!!!!!!! DO NOT EDIT MANUALLY !!!!!!!!!!! //
// !!!!! GENERATED BY CMAKE CONFIGURATION !!!!! //
//////////////////////////////////////////////////

#ifndef @CONF_TARGET_NAME@_API_H
#define @CONF_TARGET_NAME@_API_H

#define @CONF_TARGET_NAME@_IS_SHARED_LIB @CONF_IS_SHARED@

// Windows
#if defined(_WIN32) && defined(@CONF_TARGET_NAME@_BUILD_SHARED)
#define @CONF_TARGET_NAME@_API __declspec(dllexport)
#elif defined(_WIN32) && @CONF_TARGET_NAME@_IS_SHARED_LIB
#define @CONF_TARGET_NAME@_API __declspec(dllimport)
#else
#define @CONF_TARGET_NAME@_API
#endif

#endif